### ISSUE TITLE
Please add support for webp images

### ISSUE THREAD

**Issue by ghost** [dmzx/Watermark#1]
Hi dmzx,
THanks for your great extension. phpbb3.3.4 adds support for WebP images. I got Error parsing server response when upload the webp image using this extension?

The debug log:

[phpBB Debug] PHP Warning: in file [ROOT]/ext/dmzx/watermark/event/main_listener.php on line 88: imagesx() expects parameter 1 to be resource, null given
[phpBB Debug] PHP Warning: in file [ROOT]/ext/dmzx/watermark/event/main_listener.php on line 89: imagesy() expects parameter 1 to be resource, null given
[phpBB Debug] PHP Warning: in file [ROOT]/ext/dmzx/watermark/event/main_listener.php on line 94: imagecreatetruecolor(): Invalid image dimensions
[phpBB Debug] PHP Warning: in file [ROOT]/ext/dmzx/watermark/event/main_listener.php on line 95: imagealphablending() expects parameter 1 to be resource, bool given
[phpBB Debug] PHP Warning: in file [ROOT]/ext/dmzx/watermark/event/main_listener.php on line 96: imagesavealpha() expects parameter 1 to be resource, bool given
[phpBB Debug] PHP Warning: in file [ROOT]/ext/dmzx/watermark/event/main_listener.php on line 97: imagecopyresampled() expects parameter 1 to be resource, bool given
[phpBB Debug] PHP Warning: in file [ROOT]/ext/dmzx/watermark/event/main_listener.php on line 186: imagecopy() expects parameter 1 to be resource, null given
[phpBB Debug] PHP Warning: in file [ROOT]/ext/dmzx/watermark/event/main_listener.php on line 233: imagedestroy() expects parameter 1 to be resource, null given

Can you fix the bug? Thanks in advance!

**Comment by dmzx** [comment]
Hi,

I will look into this.

dmzx

**Comment by dmzx** [comment]
try with new files https://github.com/dmzx/Watermark/releases/tag/v1.0.3

**Comment by ghost** [comment]
Fixed!
😀
